// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/layout-display":{"path":"components/layout-display","id":"docs/components/layout-display","parentId":"DocLayout"},"docs/generated/design-tokens":{"path":"generated/design-tokens","id":"docs/generated/design-tokens","parentId":"DocLayout"},"docs/components/data-entry":{"path":"components/data-entry","id":"docs/components/data-entry","parentId":"DocLayout"},"docs/generated/spec-report":{"path":"generated/spec-report","id":"docs/generated/spec-report","parentId":"DocLayout"},"docs/generated/components":{"path":"generated/components","id":"docs/generated/components","parentId":"DocLayout"},"docs/components/feedback":{"path":"components/feedback","id":"docs/components/feedback","parentId":"DocLayout"},"docs/components/button":{"path":"components/button","id":"docs/components/button","parentId":"DocLayout"},"docs/components/table":{"path":"components/table","id":"docs/components/table","parentId":"DocLayout"},"docs/components/form":{"path":"components/form","id":"docs/components/form","parentId":"DocLayout"},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/theme":{"path":"theme","id":"docs/theme","parentId":"DocLayout"},"components/config-provider/index":{"id":"components/config-provider/index","path":"components/config-provider","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'E:/Code/FE/wrap-antd/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/layout-display': React.lazy(() => import(/* webpackChunkName: "docs__components__layout-display.md" */'E:/Code/FE/wrap-antd/docs/components/layout-display.md')),
'docs/generated/design-tokens': React.lazy(() => import(/* webpackChunkName: "docs__generated__design-tokens.md" */'E:/Code/FE/wrap-antd/docs/generated/design-tokens.md')),
'docs/components/data-entry': React.lazy(() => import(/* webpackChunkName: "docs__components__data-entry.md" */'E:/Code/FE/wrap-antd/docs/components/data-entry.md')),
'docs/generated/spec-report': React.lazy(() => import(/* webpackChunkName: "docs__generated__spec-report.md" */'E:/Code/FE/wrap-antd/docs/generated/spec-report.md')),
'docs/generated/components': React.lazy(() => import(/* webpackChunkName: "docs__generated__components.md" */'E:/Code/FE/wrap-antd/docs/generated/components.md')),
'docs/components/feedback': React.lazy(() => import(/* webpackChunkName: "docs__components__feedback.md" */'E:/Code/FE/wrap-antd/docs/components/feedback.md')),
'docs/components/button': React.lazy(() => import(/* webpackChunkName: "docs__components__button.md" */'E:/Code/FE/wrap-antd/docs/components/button.md')),
'docs/components/table': React.lazy(() => import(/* webpackChunkName: "docs__components__table.md" */'E:/Code/FE/wrap-antd/docs/components/table.md')),
'docs/components/form': React.lazy(() => import(/* webpackChunkName: "docs__components__form.md" */'E:/Code/FE/wrap-antd/docs/components/form.md')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'E:/Code/FE/wrap-antd/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'E:/Code/FE/wrap-antd/docs/index.md')),
'docs/theme': React.lazy(() => import(/* webpackChunkName: "docs__theme.md" */'E:/Code/FE/wrap-antd/docs/theme.md')),
'components/config-provider/index': React.lazy(() => import(/* webpackChunkName: "components__config-provider__index.md" */'E:/Code/FE/wrap-antd/src/components/config-provider/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
