// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0, demoIndex as dmi0 } from 'E:/Code/FE/wrap-antd/docs/components/layout-display.md?type=frontmatter';
import { frontmatter as fm1, toc as t1, demoIndex as dmi1 } from 'E:/Code/FE/wrap-antd/docs/generated/design-tokens.md?type=frontmatter';
import { frontmatter as fm2, toc as t2, demoIndex as dmi2 } from 'E:/Code/FE/wrap-antd/docs/components/data-entry.md?type=frontmatter';
import { frontmatter as fm3, toc as t3, demoIndex as dmi3 } from 'E:/Code/FE/wrap-antd/docs/generated/spec-report.md?type=frontmatter';
import { frontmatter as fm4, toc as t4, demoIndex as dmi4 } from 'E:/Code/FE/wrap-antd/docs/generated/components.md?type=frontmatter';
import { frontmatter as fm5, toc as t5, demoIndex as dmi5 } from 'E:/Code/FE/wrap-antd/docs/components/feedback.md?type=frontmatter';
import { frontmatter as fm6, toc as t6, demoIndex as dmi6 } from 'E:/Code/FE/wrap-antd/docs/components/button.md?type=frontmatter';
import { frontmatter as fm7, toc as t7, demoIndex as dmi7 } from 'E:/Code/FE/wrap-antd/docs/components/table.md?type=frontmatter';
import { frontmatter as fm8, toc as t8, demoIndex as dmi8 } from 'E:/Code/FE/wrap-antd/docs/components/form.md?type=frontmatter';
import { frontmatter as fm9, toc as t9, demoIndex as dmi9 } from 'E:/Code/FE/wrap-antd/docs/guide.md?type=frontmatter';
import { frontmatter as fm10, toc as t10, demoIndex as dmi10 } from 'E:/Code/FE/wrap-antd/docs/index.md?type=frontmatter';
import { frontmatter as fm11, toc as t11, demoIndex as dmi11 } from 'E:/Code/FE/wrap-antd/docs/theme.md?type=frontmatter';
import { frontmatter as fm12, toc as t12, demoIndex as dmi12 } from 'E:/Code/FE/wrap-antd/src/components/config-provider/index.md?type=frontmatter';

export const filesMeta = {
  'docs/components/layout-display': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/layout-display.md?type=text'),
  },
  'docs/generated/design-tokens': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/generated/design-tokens.md?type=text'),
  },
  'docs/components/data-entry': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/data-entry.md?type=text'),
  },
  'docs/generated/spec-report': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/generated/spec-report.md?type=text'),
  },
  'docs/generated/components': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/generated/components.md?type=text'),
  },
  'docs/components/feedback': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/feedback.md?type=text'),
  },
  'docs/components/button': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/button.md?type=text'),
  },
  'docs/components/table': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/table.md?type=text'),
  },
  'docs/components/form': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/components/form.md?type=text'),
  },
  'docs/guide': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/guide.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/index.md?type=text'),
  },
  'docs/theme': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'E:/Code/FE/wrap-antd/docs/theme.md?type=text'),
  },
  'components/config-provider/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'E:/Code/FE/wrap-antd/src/components/config-provider/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
