// This file is generated by pnpm spec:sync. Do not edit manually.
export const ComponentSidebar = [
  {
    title: '基础能力',
    children: [
      {
        title: 'Button 按钮',
        link: '/components/button',
      },
      {
        title: 'Form 表单',
        link: '/components/form',
      },
      {
        title: 'Table 表格',
        link: '/components/table',
      },
    ],
  },
  {
    title: '数据录入',
    children: [
      {
        title: 'Input 输入框',
        link: '/components/input',
      },
      {
        title: 'InputNumber 数字输入框',
        link: '/components/input-number',
      },
      {
        title: 'Select 选择器',
        link: '/components/select',
      },
      {
        title: 'DatePicker 日期选择器',
        link: '/components/date-picker',
      },
      {
        title: 'TimePicker 时间选择器',
        link: '/components/time-picker',
      },
      {
        title: 'Cascader 级联选择',
        link: '/components/cascader',
      },
      {
        title: 'TreeSelect 树选择',
        link: '/components/tree-select',
      },
      {
        title: 'Checkbox 多选框',
        link: '/components/checkbox',
      },
      {
        title: 'Radio 单选框',
        link: '/components/radio',
      },
      {
        title: 'Switch 开关',
        link: '/components/switch',
      },
      {
        title: 'Slider 滑动输入条',
        link: '/components/slider',
      },
      {
        title: 'Upload 上传',
        link: '/components/upload',
      },
      {
        title: 'Transfer 穿梭框',
        link: '/components/transfer',
      },
      {
        title: 'AutoComplete 自动完成',
        link: '/components/auto-complete',
      },
      {
        title: 'ColorPicker 颜色选择器',
        link: '/components/color-picker',
      },
      {
        title: 'Mentions 提及',
        link: '/components/mentions',
      },
      {
        title: 'Rate 评分',
        link: '/components/rate',
      },
    ],
  },
  {
    title: '数据展示',
    children: [
      {
        title: 'Card 卡片',
        link: '/components/card',
      },
      {
        title: 'Avatar 头像',
        link: '/components/avatar',
      },
      {
        title: 'Badge 徽标数',
        link: '/components/badge',
      },
      {
        title: 'Carousel 走马灯',
        link: '/components/carousel',
      },
      {
        title: 'Collapse 折叠面板',
        link: '/components/collapse',
      },
      {
        title: 'Descriptions 描述列表',
        link: '/components/descriptions',
      },
      {
        title: 'Image 图片',
        link: '/components/image',
      },
      {
        title: 'List 列表',
        link: '/components/list',
      },
      {
        title: 'Statistic 统计数值',
        link: '/components/statistic',
      },
      {
        title: 'Tag 标签',
        link: '/components/tag',
      },
      {
        title: 'Tooltip 文字提示',
        link: '/components/tooltip',
      },
      {
        title: 'Popover 气泡卡片',
        link: '/components/popover',
      },
      {
        title: 'Tour 漫游式引导',
        link: '/components/tour',
      },
      {
        title: 'Calendar 日历',
        link: '/components/calendar',
      },
      {
        title: 'Empty 空状态',
        link: '/components/empty',
      },
      {
        title: 'QRCode 二维码',
        link: '/components/qr-code',
      },
      {
        title: 'Segmented 分段控制器',
        link: '/components/segmented',
      },
      {
        title: 'Timeline 时间轴',
        link: '/components/timeline',
      },
      {
        title: 'Tree 树形控件',
        link: '/components/tree',
      },
    ],
  },
  {
    title: '反馈',
    children: [
      {
        title: 'Alert 警告提示',
        link: '/components/alert',
      },
      {
        title: 'Modal 对话框',
        link: '/components/modal',
      },
      {
        title: 'Drawer 抽屉',
        link: '/components/drawer',
      },
      {
        title: 'Popconfirm 气泡确认框',
        link: '/components/popconfirm',
      },
      {
        title: 'Progress 进度条',
        link: '/components/progress',
      },
      {
        title: 'Result 结果',
        link: '/components/result',
      },
      {
        title: 'Skeleton 骨架屏',
        link: '/components/skeleton',
      },
      {
        title: 'Spin 加载中',
        link: '/components/spin',
      },
      {
        title: 'App 包裹组件',
        link: '/components/app',
      },
      {
        title: 'message 全局提示',
        link: '/components/message',
      },
      {
        title: 'notification 通知提醒框',
        link: '/components/notification',
      },
    ],
  },
  {
    title: '导航',
    children: [
      {
        title: 'Layout 布局',
        link: '/components/layout',
      },
      {
        title: 'Pagination 分页',
        link: '/components/pagination',
      },
      {
        title: 'Tabs 标签页',
        link: '/components/tabs',
      },
      {
        title: 'Steps 步骤条',
        link: '/components/steps',
      },
      {
        title: 'Breadcrumb 面包屑',
        link: '/components/breadcrumb',
      },
      {
        title: 'Anchor 锚点',
        link: '/components/anchor',
      },
      {
        title: 'BackTop 回到顶部',
        link: '/components/back-top',
      },
      {
        title: 'Dropdown 下拉菜单',
        link: '/components/dropdown',
      },
      {
        title: 'Menu 导航菜单',
        link: '/components/menu',
      },
    ],
  },
  {
    title: '通用',
    children: [
      {
        title: 'FloatButton 悬浮按钮',
        link: '/components/float-button',
      },
      {
        title: 'Typography 排版',
        link: '/components/typography',
      },
    ],
  },
  {
    title: '其他',
    children: [
      {
        title: 'Affix 固钉',
        link: '/components/affix',
      },
      {
        title: 'Watermark 水印',
        link: '/components/watermark',
      },
    ],
  },
  {
    title: '布局',
    children: [
      {
        title: 'Divider 分割线',
        link: '/components/divider',
      },
      {
        title: 'Flex 弹性布局',
        link: '/components/flex',
      },
      {
        title: 'Grid 栅格断点',
        link: '/components/grid',
      },
      {
        title: 'Row 栅格行',
        link: '/components/row',
      },
      {
        title: 'Col 栅格列',
        link: '/components/col',
      },
      {
        title: 'Space 间距',
        link: '/components/space',
      },
      {
        title: 'Splitter 分割面板',
        link: '/components/splitter',
      },
    ],
  },
];
export const BusinessSidebar = [
  {
    title: '业务沉淀',
    children: [
      {
        title: 'ErrorBlock 空状态',
        link: '/business/error-block',
      },
      {
        title: 'Status 状态点',
        link: '/business/status',
      },
      {
        title: 'DetailPageHeader 详情页头',
        link: '/business/detail-page-header',
      },
      {
        title: 'ApprovalProgressSteps 审批进度',
        link: '/business/approval-progress-steps',
      },
    ],
  },
];
export const GeneratedSidebar = [
  {
    title: '设计规范',
    children: [
      {
        title: '组件总览',
        link: '/generated/components',
      },
      {
        title: '设计 Token',
        link: '/generated/design-tokens',
      },
      {
        title: '解析报告',
        link: '/generated/spec-report',
      },
    ],
  },
];
