// This file is generated by pnpm spec:sync. Do not edit manually.
export const globalDesignTokens = {
  color: {
    brand: {
      "1": "#FFFCF0",
      "2": "#F7F4E9",
      "3": "#DFCFB4",
      "4": "#DED3BA",
      "5": "#D1BB8E",
      "6": "#B0915C",
      "7": "#9B7235",
      "8": "#785A32",
      "9": "#523A1E",
      "10": "#2B1D10"
    },
    text: {
      primary: "rgba(0,0,0,0.85)",
      secondary: "rgba(0,0,0,0.65)",
      tertiary: "rgba(0,0,0,0.45)",
      disabled: "rgba(0,0,0,0.25)",
      inverse: "rgba(255,255,255,1)",
      inverseSecondary: "rgba(255,255,255,0.65)"
    },
    border: {
      base: "rgba(0,0,0,0.15)",
      strong: "rgba(0,0,0,0.25)",
      subtle: "rgba(0,0,0,0.12)"
    },
    fill: {
      white: "#FFFFFF",
      background: "#F4F6F8",
      layout: "#E9EBF3",
      tableHeader: "#F1F2F7",
      overlay: "rgba(0,0,0,0.30)",
      tooltip: "rgba(0,0,0,0.75)"
    },
    functional: {
      success: "#00C078",
      error: "#FF4D4F",
      warning: "#FFA000",
      info: "#1874FF"
    },
    data: [
      "rgba(91,143,249,0.85)",
      "rgba(97,221,170,0.85)",
      "rgba(101,120,157,0.85)",
      "rgba(246,189,22,0.85)",
      "rgba(114,98,253,0.85)",
      "rgba(120,211,248,0.85)",
      "rgba(150,97,188,0.85)",
      "rgba(246,144,61,0.85)",
      "rgba(0,134,133,0.85)",
      "rgba(240,139,180,0.85)"
    ],
    gradient: [
      "linear-gradient(90deg, #E9BC89, #FFCD40)",
      "linear-gradient(90deg, #3EF17D, #A5FFB6)",
      "linear-gradient(90deg, #00AAFF, #38DCF7)",
      "linear-gradient(90deg, #5A72E6, #73AFFF)",
      "linear-gradient(90deg, #FF8D00, #FFB367)"
    ]
  },
  radius: {
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    round: 100
  },
  shadow: {
    hover: "0px 3px 6px 0px rgba(0,0,0,0.12), 0px 1px 2px -2px rgba(0,0,0,0.16), 0px 5px 12px 4px rgba(0,0,0,0.09)",
    default: "0px 9px 28px 8px rgba(0,0,0,0.05), 0px 6px 16px 0px rgba(0,0,0,0.08), 0px 3px 6px -4px rgba(0,0,0,0.12)",
    modal: "0px 12px 48px 16px rgba(0,0,0,0.03), 0px 9px 28px 0px rgba(0,0,0,0.05), 0px 6px 16px -8px rgba(0,0,0,0.08)",
    tooltip: "0px 9px 28px 8px rgba(0,0,0,0.05), 0px 6px 16px 0px rgba(0,0,0,0.08), 0px 3px 7px -4px rgba(0,0,0,0.12)"
  },
  space: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
    gridGutter: 20
  },
  typography: {
    fontFamily: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    body: {
      fontSize: 14,
      lineHeight: 1.5714285714285714,
      fontWeight: 400
    },
    title: {
      fontSize: 20,
      lineHeight: 1.4,
      fontWeight: 500
    }
  },
  layout: {
    headerHeight: 64,
    siderExpandedWidth: 208,
    siderCollapsedWidth: 48,
    contentPadding: "20px 16px",
    pageMarginXl: 261,
    pageMarginLg: 120,
    pageMarginBase: 24,
    subNavHeight: 48,
    tertiaryNavHeight: 40
  },
  imageRatio: {
    square: "1 / 1",
    classic: "4 / 3",
    golden: "3 / 2",
    widescreen: "16 / 9",
    ultraWide: "2 / 1"
  }
} as const;

export type GlobalDesignTokens = typeof globalDesignTokens;
