// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from 'E:/Code/FE/wrap-antd/node_modules/.pnpm/rc-util@5.44.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from 'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"wrap-antd","description":"Enterprise UI wrapper and business component library based on Ant Design v5.","version":"0.1.0"};
const historyType = "browser";
const hostname = "";
const themeConfig = {"footer":"基于 Ant Design v5 的企业级 UI 封装","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"wrap-antd","nav":[{"title":"指南","link":"/guide"},{"title":"主题","link":"/theme"},{"title":"组件","link":"/components/config-provider"}],"sidebar":{"/components":[{"title":"基础能力","children":[{"title":"ConfigProvider","link":"/components/config-provider"},{"title":"Button 按钮","link":"/components/button"},{"title":"Form 表单","link":"/components/form"},{"title":"Table 表格","link":"/components/table"},{"title":"Data Entry 数据录入","link":"/components/data-entry"},{"title":"Feedback 反馈","link":"/components/feedback"},{"title":"Layout 展示布局","link":"/components/layout-display"},{"title":"自动生成组件","link":"/generated/components"}]},{"title":"设计规范","children":[{"title":"设计 Token","link":"/generated/design-tokens"},{"title":"解析报告","link":"/generated/spec-report"}]}]}};
const _2_level_nav_available = false;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
