// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from 'E:/Code/FE/wrap-antd/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from 'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
