import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import {
  businessDocs,
  componentDocs,
  configProviderDoc,
  renderComponentDoc,
  renderStandaloneDoc,
} from './docs-generator.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const isCheck = process.argv.includes('--check');
const generatedFiles = new Map();

const fileHeader = `// This file is generated by pnpm spec:sync. Do not edit manually.\n`;

const matchAll = (source, pattern, mapper = (match) => match[0]) =>
  [...source.matchAll(pattern)].map(mapper);

const firstMatch = (source, pattern, fallback = '') =>
  source.match(pattern)?.[1]?.trim() ?? fallback;

const toTs = (value) => JSON.stringify(value, null, 2).replace(/"([a-zA-Z_$][\w$]*)":/g, '$1:');

const parserByExtension = {
  '.css': 'css',
  '.md': 'markdown',
  '.ts': 'typescript',
};

const formatGeneratedContent = async (relativePath, content) => {
  const parser = parserByExtension[path.extname(relativePath)];
  if (!parser) return content;
  const filepath = path.join(rootDir, relativePath);
  const config = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(content, { ...config, filepath, parser });
};

const addFile = async (relativePath, content) => {
  generatedFiles.set(
    path.join(rootDir, relativePath),
    await formatGeneratedContent(relativePath, content),
  );
};

const themeTokenDir = path.join(rootDir, 'src', 'theme', 'tokens');
const readThemeToken = (file) => readFileSync(path.join(themeTokenDir, file), 'utf8');

const themeSource = {
  primitive: readThemeToken('primitive-tokens.ts'),
  semantic: readThemeToken('semantic-tokens.ts'),
  antd: readThemeToken('antd-tokens.ts'),
  antdComponent: readThemeToken('antd-component-tokens.ts'),
  wplusComponent: readThemeToken('wplus-component-tokens.ts'),
};

const themeSourceText = Object.values(themeSource).join('\n');
const rawConstValues = Object.fromEntries(
  matchAll(themeSourceText, /export const ([A-Z][A-Z0-9_]*)\s*=\s*([^;\n]+);/g, (m) => [
    m[1],
    m[2].trim(),
  ]),
);

const themeConstValues = {};
const resolveThemeValue = (value) => {
  const normalized = String(value).trim();
  if (/^'.*'$/.test(normalized)) return normalized.slice(1, -1);
  if (/^\d+(?:\.\d+)?$/.test(normalized)) return Number(normalized);
  return themeConstValues[normalized] ?? rawConstValues[normalized] ?? normalized;
};

for (let index = 0; index < 4; index += 1) {
  for (const [name, value] of Object.entries(rawConstValues)) {
    themeConstValues[name] = resolveThemeValue(value);
  }
}

const blockContent = (source, name) =>
  firstMatch(source, new RegExp(`export const ${name}[^=]*=\\s*([\\s\\S]*?)\\s*] as const;`));

const sourceBrandEntries = matchAll(
  themeSource.primitive,
  /export const BRAND_(\d+)\s*=\s*'([^']+)'/g,
  (m) => [Number(m[1]), m[2]],
).sort(([a], [b]) => a - b);

const sourceDataColors = matchAll(
  blockContent(themeSource.primitive, 'DATA_COLORS'),
  /'([^']+)'/g,
  (m) => m[1],
);

const sourceGradientEntries = matchAll(
  firstMatch(themeSource.primitive, /export const GRADIENTS\s*=\s*({[\s\S]*?}) as const;/),
  /(\w+):\s*'([^']+)'/g,
  (m) => [m[1], m[2]],
);

const sourceRadiusEntries = matchAll(
  blockContent(themeSource.primitive, 'RADIUS_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?radius:\s*'([^']+)'/g,
  (m) => [m[1], m[2]],
);

const sourceShadowEntries = matchAll(
  blockContent(themeSource.primitive, 'SHADOW_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?boxShadow:\s*([^,\n]+)/g,
  (m) => [m[1], resolveThemeValue(m[2])],
);

const sourceSpacingEntries = matchAll(
  firstMatch(themeSource.primitive, /export const wplusSpacing\s*=\s*({[\s\S]*?}) as const;/),
  /(\w+):\s*(\d+)/g,
  (m) => [m[1], Number(m[2])],
);

const sourceTypographyEntries = matchAll(
  blockContent(themeSource.primitive, 'TYPOGRAPHY_TOKENS'),
  /key:\s*'([^']+)'[\s\S]*?label:\s*'([^']+)'[\s\S]*?fontSize:\s*([^,\n]+)[\s\S]*?lineHeight:\s*([^,\n]+)[\s\S]*?fontWeight:\s*([^,\n]+)/g,
  (m) => [
    m[1],
    {
      label: m[2],
      fontSize: resolveThemeValue(m[3]),
      lineHeight: resolveThemeValue(m[4]),
      fontWeight: resolveThemeValue(m[5]),
    },
  ],
);

const sourceAntdTokenEntries = matchAll(
  firstMatch(themeSource.antd, /export const antdTokens\s*=\s*({[\s\S]*?})\s*as const;/),
  /^\s{4}([a-zA-Z]\w+):\s*([^,\n]+)/gm,
  (m) => [m[1], resolveThemeValue(m[2])],
);

const sourceTheme = {
  brand: Object.fromEntries(sourceBrandEntries),
  dataColors: sourceDataColors,
  gradients: Object.fromEntries(sourceGradientEntries),
  radius: Object.fromEntries(sourceRadiusEntries),
  shadows: Object.fromEntries(sourceShadowEntries),
  spacing: Object.fromEntries(sourceSpacingEntries),
  typography: Object.fromEntries(sourceTypographyEntries),
  antdTokens: Object.fromEntries(sourceAntdTokenEntries),
  componentTokenCount: matchAll(themeSource.antdComponent, /^\s{4}[A-Z]\w+:\s*{/gm).length,
  wplusComponentTokenCount: matchAll(themeSource.wplusComponent, /^\s{2}[a-zA-Z]\w+:\s*{/gm).length,
};

const componentTypeNames = componentDocs
  .map((doc) => doc.typeName)
  .filter((typeName) => Boolean(typeName))
  .filter((typeName, index, typeNames) => typeNames.indexOf(typeName) === index);

const toSlug = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const sidebarItem = (title, link) => ({ title, link });

const componentCategories = [...new Set(componentDocs.map((doc) => doc.category))];
const ComponentSidebar = componentCategories
  .map((category) => ({
    title: category,
    children: componentDocs
      .filter((doc) => doc.category === category)
      .map((doc) => sidebarItem(doc.title, `/components/${toSlug(doc.name)}`)),
  }))
  .filter((group) => group.children.length);

const BusinessSidebar = [
  {
    title: '业务沉淀',
    children: businessDocs.map((doc) =>
      sidebarItem(doc.title, `/${doc.path.replace(/^docs\//, '').replace(/\.md$/, '')}`),
    ),
  },
];

const GeneratedSidebar = [
  {
    title: '设计规范',
    children: [
      sidebarItem('组件总览', '/generated/components'),
      sidebarItem('设计 Token', '/generated/design-tokens'),
      sidebarItem('解析报告', '/generated/spec-report'),
    ],
  },
];

await addFile(
  'src/components/generated/index.ts',
  `${fileHeader}export { ${componentDocs.map((doc) => doc.name).join(', ')} } from 'antd';\nexport type { ${componentTypeNames.join(', ')} } from 'antd';\n`,
);

await addFile(
  'src/components/generated/sidebar.generated.ts',
  `${fileHeader}export const generatedComponentSidebar = ${toTs(ComponentSidebar)};\n`,
);

await addFile(
  'dumi.sidebar.ts',
  `${fileHeader}export const ComponentSidebar = ${toTs(ComponentSidebar)};
export const BusinessSidebar = ${toTs(BusinessSidebar)};
export const GeneratedSidebar = ${toTs(GeneratedSidebar)};
`,
);

for (const [index, doc] of componentDocs.entries()) {
  await addFile(`docs/components/${toSlug(doc.name)}.md`, renderComponentDoc(doc, 100 + index));
}

for (const [index, doc] of businessDocs.entries()) {
  await addFile(doc.path, renderStandaloneDoc(doc, 200 + index));
}

await addFile(configProviderDoc.path, renderStandaloneDoc(configProviderDoc, 1));

await addFile(
  'docs/generated/design-tokens.md',
  `---
title: 设计 Token
order: 100
---

# 设计 Token

本页由 \`pnpm spec:sync\` 根据 \`src/theme/tokens\` 自动生成。

## 品牌色

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.brand)
  .map(([key, value]) => `| Brand ${key} | \`${value}\` |`)
  .join('\n')}

## 数据色

| Index | Value |
| --- | --- |
${sourceTheme.dataColors.map((value, index) => `| ${index + 1} | \`${value}\` |`).join('\n')}

## 渐变色

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.gradients)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## 圆角

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.radius)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## 阴影

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.shadows)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}

## 间距

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.spacing)
  .slice(0, 24)
  .map(([key, value]) => `| ${key} | \`${value}px\` |`)
  .join('\n')}

## Ant Design 全局 Token

| Token | Value |
| --- | --- |
${Object.entries(sourceTheme.antdTokens)
  .slice(0, 32)
  .map(([key, value]) => `| ${key} | \`${value}\` |`)
  .join('\n')}
`,
);

await addFile(
  'docs/generated/components.md',
  `---
title: 自动生成组件
order: 110
---

# 自动生成组件

以下组件文档和显式导出清单由 \`pnpm spec:sync\` 自动生成。顺序按 Ant Design 官方组件导航排列，新增范围以当前依赖的 Ant Design v5.29.3 实际导出为准。

| 分类 | 组件 | 用法 |
| --- | --- | --- |
${componentDocs
  .map(
    (doc) =>
      `| ${doc.category} | ${doc.title} | \`import { ${doc.name} } from 'privatebank-design'\` |`,
  )
  .join('\n')}
`,
);

await addFile(
  'docs/generated/spec-report.md',
  `---
title: 解析报告
order: 120
---

# 解析报告

本页由 \`pnpm spec:sync\` 自动生成，用于检查源码 token 与文档生成结果。

## 已识别

- 主题来源：\`src/theme/tokens\`
- 品牌色：${Object.keys(sourceTheme.brand).length} 项
- 数据色：${sourceTheme.dataColors.length} 项
- 渐变色：${Object.keys(sourceTheme.gradients).length} 项
- 圆角 token：${Object.keys(sourceTheme.radius).length} 项
- 阴影 token：${Object.keys(sourceTheme.shadows).length} 项
- 间距 token：${Object.keys(sourceTheme.spacing).length} 项
- 字体层级：${Object.keys(sourceTheme.typography).length} 项
- antd 全局 token：${Object.keys(sourceTheme.antdTokens).length} 项
- antd 组件 token 分组：${sourceTheme.componentTokenCount} 项
- W+ 组件 token 分组：${sourceTheme.wplusComponentTokenCount} 项
- 自动导出组件/API：${componentDocs.length} 个
- 业务组件文档：${businessDocs.length} 个

## 处理原则

- 文档中的设计 Token 以 \`src/theme/tokens\` 为准。
- antd 组件顺序对齐官方组件导航，组件范围对齐当前安装的 Ant Design v5.29.3。
- 已有 wrapper 继续由包入口覆盖，同名 API 与 Ant Design 保持兼容。
`,
);

await addFile(
  'docs/theme.md',
  `---
title: 主题定制
order: 2
---

# 主题定制

\`privatebank-design\` 通过 \`wplusTheme\` 统一维护企业主题，并在包装版 \`ConfigProvider\` 中默认合并。

当前主题以 \`src/theme/tokens\` 为事实来源：

| 源码文件 | 落地方式 |
| --- | --- |
| \`src/theme/tokens/primitive-tokens.ts\` | 品牌色、数据色、渐变、圆角、阴影、间距和字体层级 |
| \`src/theme/tokens/semantic-tokens.ts\` | 业务语义色、文字色、背景色、边框色 |
| \`src/theme/tokens/antd-tokens.ts\` | Ant Design 全局 token |
| \`src/theme/tokens/antd-component-tokens.ts\` | Ant Design 组件级 token |
| \`src/theme/tokens/wplus-component-tokens.ts\` | W+ 组件语义 token |

## 内置 token

\`\`\`tsx
import { BRAND_COLORS, Button, ConfigProvider } from 'privatebank-design';

export default () => (
  <ConfigProvider>
    <Button type="primary">{BRAND_COLORS.brand7}</Button>
  </ConfigProvider>
);
\`\`\`

## 覆盖主题

\`\`\`tsx
import { Button, ConfigProvider } from 'privatebank-design';

export default () => (
  <ConfigProvider theme={{ token: { colorPrimary: '#0052d9', borderRadius: 6 } }}>
    <Button type="primary">企业主按钮</Button>
  </ConfigProvider>
);
\`\`\`

## 复用完整主题

\`\`\`tsx
import { Button, ConfigProvider, wplusTheme } from 'privatebank-design';

export default () => (
  <ConfigProvider theme={wplusTheme}>
    <Button type="primary">W+ 主题按钮</Button>
  </ConfigProvider>
);
\`\`\`

## CSS 变量

引入 \`privatebank-design/reset.css\` 后可使用基础 CSS 变量：

\`\`\`css
.page {
  background: var(--wplus-color-bg-page);
  padding: var(--wplus-layout-content-padding);
}

.cover {
  aspect-ratio: var(--wplus-image-ratio-widescreen);
  border-radius: var(--wplus-radius-md);
}
\`\`\`
`,
);

const writeOrCheck = () => {
  let hasDiff = false;

  for (const [file, content] of generatedFiles) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;

    if (current !== content) {
      hasDiff = true;
      if (isCheck) {
        console.error(`Generated file is out of date: ${path.relative(rootDir, file)}`);
      } else {
        mkdirSync(path.dirname(file), { recursive: true });
        writeFileSync(file, content);
      }
    }
  }

  if (isCheck && hasDiff) {
    process.exitCode = 1;
    return;
  }

  console.log(
    isCheck ? 'Generated files are up to date.' : 'Generated files synced from theme tokens.',
  );
};

writeOrCheck();
