// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/Code/FE/wrap-antd/node_modules/.pnpm/dumi@2.4.30_@babel+core@7.29.7_@swc+helpers@0.5.15_@types+node@25.9.3_@types+react@18.3.31_es_aems3bbcd6dszd3gyjuprosb3y/node_modules/dumi/theme-default/builtins/API/index.js';
